title: Souri Maddipatti
avatar: selfpic.jpg
logo: selfpic.jpg
description: Data Analyst|Data Modeling| Data Visualization| Senior PM |Tableau | Excel| Life Sciences | Business  Analysis |Change Management| SDLC| Waterfall| Agile 
show_downloads: true
theme: jekyll-theme-minimal
