title: Souri Maddipatti
avatar: selfpic.jpg
logo: /assets/images/selfpic.jpg
description: Data Analyst|Senior PM |GxP | GMP| QMS| LIMS| Life Sciences | Business  Analysis | Quality Systems | Reg Compliance |Change Management| SDLC| Waterfall| Agile 
show_downloads: true
theme: jekyll-theme-minimal
