title: Souri Maddipatti
logo:selfpic.jpg
description: Data Analyst|Senior PM | Project Manager |GxP | GMP| QMS| LIMS| Life Sciences | Pharma | Biotechnology | Business  Analysis | Quality Systems | Reg Compliance | Quality SME | EDMS | LMS | Change Management| SDLC| Waterfall| Agile 
show_downloads: true
theme: jekyll-theme-minimal
